Domaska 4 by Shemyakin Nikita
itmo2022-verstka/task-4 pull request #1
Opened 2022-12-20 19:55 UTC by JelluSandro

2023-01-14 07:14 UTC, trixartem requested changes

2023-01-14 07:14 UTC, trixartem commented on catgram/src/index.html
> +  <svg display="none">
Инлайнить svg не самый лучший вариант - лучше положить в отдельный файл. Еще в задании есть пункт  "Иконки контролов нужно реализовать с использованием svg-спрайта, его вы должны сами собрать"

2023-01-14 07:14 UTC, trixartem commented on catgram/src/index.css
> +.right-arrow {
Кнопки наезжают на картинки и на мобильном телефоне верстка не как на макете
![image](https://user-images.githubusercontent.com/2376007/212460598-1a3c69a3-9ce5-4630-bc15-5b6026e88b96.png)

2023-01-14 07:14 UTC, trixartem commented on catgram/src/index.css
> +  width: 900px;
Этот эффект должен работать по-другому. При нажатии картинка должна вписываться в квадрат, а при следующем нажатии картинка заполняет весь квадрат

2023-01-22 20:17 UTC, JelluSandro commented
@trixartem все исправил

2023-01-23 20:16 UTC, trixartem commented
✅ Принято

2023-01-23 20:16 UTC, closed without merging