Юльцова Наталья M33351
itmo2022-verstka/task-4 pull request #14
Opened 2023-01-08 23:21 UTC by yults

2023-01-24 20:26 UTC, trixartem commented
Неправильно работает кнопка "Вмещаемость". Изображение либо должно вписываться в квадрат, либо заполнять. Сейчас меняется размер контейнера.
![image](https://user-images.githubusercontent.com/2376007/214401058-4b75040b-3923-479f-9160-cf06d7983a5c.png)

2023-01-24 20:26 UTC, trixartem commented
Нет анимации на применение фильтров

2023-01-24 20:27 UTC, trixartem requested changes

2023-01-24 20:27 UTC, trixartem commented on catgram/src/index.html
> +      <svg xmlns="http://www.w3.org/2000/svg" class="tohide">
Надо вынести в отдельный файл

2023-01-25 00:56 UTC, yults commented
Случайно запушила  с своего 2 аккаунта в гит, но все исправлено

2023-01-26 19:29 UTC, trixartem commented
✅ Принято

2023-01-26 19:29 UTC, closed without merging