Галибов Михаил Олегович
itmo2022-verstka/task-4 pull request #15
Opened 2023-01-09 17:21 UTC by Gram3r

2023-01-24 20:35 UTC, trixartem requested changes

2023-01-24 20:35 UTC, trixartem commented on catgram/src/index.html
> +<svg width="48px" height="48px" xmlns="http://www.w3.org/2000/svg">
Нужно вынести в отдельный файл

2023-01-24 20:35 UTC, trixartem commented on catgram/src/index.css
> +    transition: 1s;
Для всех видов изменений?

2023-01-26 10:31 UTC, Gram3r commented on catgram/src/index.html
> +<svg width="48px" height="48px" xmlns="http://www.w3.org/2000/svg">
fixed

2023-01-26 10:36 UTC, Gram3r commented on catgram/src/index.css
> +    transition: 1s;
Да, благодаря тому, что я навесил над главным изображением этот transition, все операции имеют данный параметр. Разве это плохо или как-то не верно сделано по условию?

2023-01-26 19:32 UTC, trixartem commented on catgram/src/index.css
> +    transition: 1s;
Так может появиться лишняя анимация

2023-01-26 19:35 UTC, trixartem commented
✅ Принято

2023-01-26 19:35 UTC, closed without merging