Купчик Антон
itmo2022-verstka/task-4 pull request #16
Opened 2023-01-10 18:32 UTC by tattosha01

CatGram

2023-03-17 19:54 UTC, trixartem requested changes
Поправь, пожалуйста кнопка - сложно проверять

2023-03-17 19:54 UTC, trixartem commented on catgram/src/index.css
> +.controls {
У контролов нет размера и они становятся некликабельными, если картинка не загрузилась

2023-03-19 20:03 UTC, tattosha01 commented on catgram/src/index.css
> +.controls {
Хмм. Я сейчас попробовал у всего(и контролов и котика) поменять url до картинки, работает
<img width="654" alt="image" src="https://user-images.githubusercontent.com/62402039/226205853-3ffa82e5-68e4-4ddb-a305-64d3f4d0baec.png">

2023-03-22 20:25 UTC, trixartem commented
✅ Принято

2023-03-22 20:25 UTC, closed without merging