Потехин Денис
itmo2022-verstka/task-4 pull request #2
Opened 2022-12-20 23:42 UTC by DenisPotekhin2002

task-4

2023-01-14 07:27 UTC, trixartem requested changes
- ❌ Не работает пункт "вмещаемость (вписано в квадрат/показано целиком)"
- ✅ Фильтры применяются без анимации

2023-01-14 07:27 UTC, trixartem commented on catgram/src/index.css
> +  left: calc((100% - 606px) / 2 - 40px);
Не очень понятны вычисления. Надо добавить комментарий

2023-01-14 07:27 UTC, trixartem commented on catgram/src/index.css
> +  -webkit-transition: transform ease-in-out .5s, opacity ease-in-out .5s;
Префиксы лишние

2023-01-14 07:27 UTC, trixartem commented on catgram/src/index.css
> +  transition: all 2s ease-in-out;
очень длинная анимация

2023-01-14 07:27 UTC, trixartem commented on catgram/src/index.css
> +#up:checked ~ .footer .filters .slider .slides img {
Вместо img лучше использовать уникальный класс

2023-01-14 07:27 UTC, trixartem commented on catgram/src/index.html
> +<svg width="0" height="0" class="hidden">
В задании нужно сделать svg-спрайт и использовать его

2023-01-14 07:27 UTC, trixartem commented on catgram/src/index.html
> +            d="M198.800 0.600 C 198.800 0.930,198.620 1.200,198.400 1.200 C 198.180 1.200,197.654 1.546,197.230 1.970 C 196.807 2.393,196.042 2.961,195.530 3.232 C 195.019 3.503,193.336 4.732,191.791
Стрелки надо выровнять по вертикали(см макет)
![image](https://user-images.githubusercontent.com/2376007/212461136-8ee243b0-5480-46c6-9bed-97ba96c1e9db.png)

2023-01-14 11:12 UTC, DenisPotekhin2002 commented
> * Не работает пункт "вмещаемость (вписано в квадрат/показано целиком)"
> 
>     * Фильтры применяются без анимации

Почему "квадрат-целиком" не работает, вот же
![изображение](https://user-images.githubusercontent.com/79590238/212469160-b5876a21-3c89-427e-a30f-3445dc5a3a9c.png)
![изображение](https://user-images.githubusercontent.com/79590238/212469168-b1483856-3656-4f2c-963b-cdba2365c4d5.png)

2023-01-14 11:15 UTC, DenisPotekhin2002 commented
> > * Не работает пункт "вмещаемость (вписано в квадрат/показано целиком)"
> >   
> >   * Фильтры применяются без анимации
> 
> Почему "квадрат-целиком" не работает, вот же при нажатии на эту иконку (самую левую) фотка обрезается под квадрат или возвращается обратно) ![изображение](https://user-images.githubusercontent.com/79590238/212469160-b5876a21-3c89-427e-a30f-3445dc5a3a9c.png) ![изображение](https://user-images.githubusercontent.com/79590238/212469168-b1483856-3656-4f2c-963b-cdba2365c4d5.png)

![изображение](https://user-images.githubusercontent.com/79590238/212469235-2fae22b9-150c-4530-b994-3084bc042602.png)
![изображение](https://user-images.githubusercontent.com/79590238/212469245-23024493-de82-48da-bba0-d954ecc20eaf.png)
вот из другого браузера, тоже работает

2023-01-14 11:48 UTC, DenisPotekhin2002 commented on catgram/src/index.css
> +  -webkit-transition: transform ease-in-out .5s, opacity ease-in-out .5s;
Это, вроде, для поддержки в разных браузерах, если Вы про -webkit, -o, -moz. Где-то читал, что просто transition не везде работает

2023-01-14 15:33 UTC, DenisPotekhin2002 commented on catgram/src/index.html
> +<svg width="0" height="0" class="hidden">
Так это и есть svg-спрайт же. Ну, один из вариантов (https://habr.com/ru/post/276463/, https://siteok.org/blog/html/svg-sprajty). У меня в одном svg много внутренних с тегом symbol, просто я использую их по use. Или что имелось в виду? Если просто вставить одну картинку, объединяющую много иконок внутри, их же очень неудобно будет выбирать, менять checked у кнопок и все такое

2023-01-14 20:49 UTC, DenisPotekhin2002 commented
> * Не работает пункт "вмещаемость (вписано в квадрат/показано целиком)"
> 
>     * Фильтры применяются без анимации

А, я понял, почему Вам казалось, что "вмещаемость" не работает - у меня изначально высота картинки стоит 500px, чтобы она слишком много места в высоту не занимала. И поэтому до увеличения "вписано в квадрат" это то же самое, что "показана целиком". Могу это убрать и сделать настоящую высоту, но тогда будет менее красиво, по-моему

2023-01-14 20:57 UTC, DenisPotekhin2002 commented
Изменил так, чтобы нажатие на кнопку вмещаемости имело заметное глазом действие без увеличения картинки до этого

2023-01-14 21:13 UTC, DenisPotekhin2002 commented
И можете, пожалуйста, если будете смотреть изменения здесь, посмотреть еще по второй домашке: https://github.com/itmo2022-verstka/task-2/pull/3? Я там ещё 2 недели назад всё запушил, но не знаю, где об этом сообщить

2023-01-15 09:54 UTC, trixartem commented on catgram/src/index.css
> +  -webkit-transition: transform ease-in-out .5s, opacity ease-in-out .5s;
Очень маленький процент(https://caniuse.com/?search=transition)

2023-01-15 09:55 UTC, trixartem commented on catgram/src/index.html
> +<svg width="0" height="0" class="hidden">
Картинку лучше вставлять отдельным файлом - так будет меньше мусора в коде и будет работать кэш на картинки

2023-01-15 09:57 UTC, trixartem commented on catgram/src/index.css
> +  transition: all 2s ease-in-out;
✅

2023-01-15 09:58 UTC, trixartem commented on catgram/src/index.html
> +            d="M198.800 0.600 C 198.800 0.930,198.620 1.200,198.400 1.200 C 198.180 1.200,197.654 1.546,197.230 1.970 C 196.807 2.393,196.042 2.961,195.530 3.232 C 195.019 3.503,193.336 4.732,191.791
✅

2023-01-15 10:00 UTC, trixartem commented
> Почему "квадрат-целиком" не работает, вот же при нажатии на эту иконку (самую левую) фотка обрезается под квадрат или возвращается обратно)

Картинка должна либо вписывать в квадрат, либо полностью его заполнять. А сейчас при нажатии на кнопку - увеличивается высота. В инстаграмме такой же эффект есть, когда фотография вытянута

2023-01-15 10:03 UTC, trixartem commented
Жду:
- Иконки в отдельном файле
- Эффект вмещаемости картинки(вписано в квадрат/показано целиком)

2023-01-16 01:09 UTC, DenisPotekhin2002 commented on catgram/src/index.html
> +<svg width="0" height="0" class="hidden">
Почему-то оно отказывается работать в виде отдельного файла, хотя код ровно такой же, как был в html-е и работал, а путь к файлу точно правильный. Пытаюсь нагуглить, нахожу людей с похожими проблемами, но не нахожу ответов

2023-01-16 11:56 UTC, DenisPotekhin2002 commented on catgram/src/index.html
> +<svg width="0" height="0" class="hidden">
Много где рекомендуют таки копировать и вставлять прямо в html

2023-01-16 13:05 UTC, DenisPotekhin2002 commented
Потыкал в разные места, почитал в интернете на разных сайтах - локально это не сделать никак, чтобы использовать xlink:href и ссылку на иконку, определённую во внешнем файле, нужен сервер, HTTP-запрос (что логично), а мы же сервер не поднимаем, тут просто набор html, css и svg файлов. Если поднять сервер, где можно будет обмениваться реквестами, то можно вернуться к предыдущему моему коммиту - там svg-шка в отдельном файле sprite.svg, а в html оно используется через use и href. Сейчас просто это так не заработает, поэтому откатил

2023-01-16 13:47 UTC, DenisPotekhin2002 commented
Всё сделал. Простите за много коммитов, я там пару раз замечал, что ещё что-то ломалось, пока чинил предыдущее, и исправлял. Тестировать сейчас только на сервере можно, потому что иконки подгружаются по HTTP-запросам (локально, через открытие .html-файла в браузере они подгружаться не будут), но на локалхосте все работает так, как должно.

2023-01-16 18:56 UTC, trixartem commented
Совсем иконки пропали 
 
![image](https://user-images.githubusercontent.com/2376007/212748914-1284c347-94bf-476e-a7f6-0ee5939135da.png)

2023-01-16 18:59 UTC, trixartem commented on catgram/src/index.html
> +    <svg class="icon">
Почему так сложно?
Каждая иконка кладется в отдельный svg-файл. Затем при помощи тулзы собирается один спрайт файл. Потом подключается через background и background-position позиционируется на нужной иконке

2023-01-16 19:04 UTC, trixartem commented
Так, кажется я понял в чем дело. В svg-спрайтах действительно несколько вариантов подключения.
Вот [тут](https://habr.com/ru/post/276463/) я ожидал бы самый первый, как я и рассказывал в лекции.

2023-01-16 19:06 UTC, trixartem commented
✅ Задание засчитано. Но попробуйте вариант, который я предложил

2023-01-16 19:06 UTC, closed without merging