Абичев Арсений M33351
itmo2022-verstka/task-4 pull request #3
Opened 2022-12-21 17:41 UTC by abichevarsenii

2023-01-14 07:38 UTC, trixartem requested changes
- При нажатии на кнопку "масштабирование" сама картинка увеличивается на широких экранах 
![image](https://user-images.githubusercontent.com/2376007/212461653-3d28d76f-ad39-4ad0-aa38-c451be37f314.png)
- Есть небольшие комментарии по коду

🔥 за аккуратную верстку

2023-01-14 07:38 UTC, trixartem commented on catgram/src/index.css
> +  position: fixed;
А для чего тут fixed?

2023-01-14 07:38 UTC, trixartem commented on catgram/src/index.css
> +  margin: 2vh;
На маленьких экранах выглядит не очень
![image](https://user-images.githubusercontent.com/2376007/212461504-1cbf4353-40e3-4a48-9ad3-44032b8e99d5.png)

2023-01-14 07:38 UTC, trixartem commented on catgram/src/index.html
> +            <img class="tools-img" src="icons/scale_icon.svg" alt="tool">
В задании нужно использовать спрайты

2023-01-14 07:38 UTC, trixartem commented on catgram/src/index.html
> +      <div class="main-photo-wrapper">
Можно добавить семантики

2023-01-14 07:38 UTC, trixartem commented on catgram/src/index.css
> +  margin-bottom: 4%;
Лучше все таки использовать px, потому что проценты используются для соблюдения пропорций при масштабировании

2023-01-17 18:17 UTC, trixartem commented
Все иконки пропали

2023-01-17 18:49 UTC, abichevarsenii commented
Почему-то `<use xlink:href="icons/sprite.svg#id"></use>` не работает локально, только через виртуальный сервер. Вроде из-за настроек безопасности браузера. Можно мне тогда заинлайнить код svg в index.html? Потому что другого способа использовать svg sprite я не нашёл. Или мне импортировать каждую иконку через css : `url('icons/name.svg')`? Но тогда это будет несколько файлов, а sprite, как я понял, подразумевает один файл.

2023-01-17 18:51 UTC, trixartem commented
✅ Я приму решение, потому что действительно через html работает. Вообще я имел в виду 1й способ(https://habr.com/ru/post/276463/)

2023-01-17 18:51 UTC, closed without merging