Утюжников Дмитрий M3339
itmo2022-verstka/task-4 pull request #5
Opened 2022-12-22 17:30 UTC by DimaUtyuz

2023-01-14 07:57 UTC, trixartem requested changes

2023-01-14 07:57 UTC, trixartem commented on catgram/src/index.html
> +    <svg width="0" height="0" class="hidden">
Лучше спрайт вынести в отдельный файл - сильно мусорится код

2023-01-14 07:57 UTC, trixartem commented on catgram/src/index.html
> +        <div class="img-rotate">
Не забывай про семантику

2023-01-14 07:57 UTC, trixartem commented on catgram/src/index.css
> +  margin-right: auto;
На узких экранах слишком большие отступы 
![image](https://user-images.githubusercontent.com/2376007/212462214-d725506f-19d2-4f3b-affe-05de2b4e3c36.png)

2023-01-14 07:57 UTC, trixartem commented on catgram/src/index.css
> +.checkbox-default:checked ~ .main-img .img-default {
- Не отображается иконка у кнопки
- При нажатии почему-то картинка начинает крутиться. Ожидается что при нажатии показывается картинка без фильтров и изменений, а при повторном нажатии фильтры возвращаются.

2023-01-18 12:41 UTC, DimaUtyuz commented on catgram/src/index.html
> +    <svg width="0" height="0" class="hidden">
Вынес. До этого были проблемы с тем, что картинка с градиентом не отображалась, если спрайт в отдельном файле

2023-01-18 12:44 UTC, DimaUtyuz commented on catgram/src/index.css
> +.checkbox-default:checked ~ .main-img .img-default {
В некоторых браузерах картинка почему-то не отображалась - заменил на новую.
При нажатии картинка крутилась, потому что была анимация перехода из -270 градусов в -360, чтобы при четвертом повороте картинка не крутилась в обратную сторону на 0. Поэтому возникал такой эффект. Убрал эффект

2023-01-18 12:48 UTC, DimaUtyuz commented on catgram/src/index.html
> +        <div class="img-rotate">
Что нужно исправить? Что-то не так с img-rotate?

2023-01-18 13:05 UTC, DimaUtyuz commented on catgram/src/index.css
> +  margin-right: auto;
По [условию](https://github.com/itmo2022-verstka/task-4/blob/main/README.md?plain=1#L26) сказано, что должна быть фиксированная ширина.
Было 600px - сделал 800px

2023-01-23 20:19 UTC, trixartem commented
✅ Принято

2023-01-23 20:19 UTC, closed without merging