Бессонницын Евгений M33341
itmo2022-verstka/task-4 pull request #6
Opened 2022-12-22 20:50 UTC by Turukmokto

Реализовано пролистывание фильтров

2023-01-14 08:04 UTC, trixartem requested changes
Есть небольшие комментарии

2023-01-14 08:04 UTC, trixartem commented on catgram/src/index.html
> +    <svg width="48px" height="48px" xmlns="http://www.w3.org/2000/svg">
Лучше вынести в отдельный файл, так будет код выглядеть чище и картинка будет кэшироваться при повторной загрузке

2023-01-14 08:04 UTC, trixartem commented on catgram/src/index.css
> +.arrow-static-l,
Надо выровнять стрелки (см макет)
![image](https://user-images.githubusercontent.com/2376007/212462546-56548afc-59de-47fa-9a2e-ac19bb046433.png)

2023-01-14 08:04 UTC, trixartem commented on catgram/src/index.css
> +.input-fill:checked ~ .kitty .image-flipped,
При нажатии на кнопку, картинка меняет размер, а она должна либо вписываться в квадрат, либо заполнять его

2023-01-15 17:08 UTC, Turukmokto commented
@trixartem Добрый вечер, я поправил все замечания, прошу проверить новую версию.
1 + Подгружаю иконки из svg файлов в папке icons, а не из html кода
2 + Стрелки теперь по середине картинок
3 + Убрал изменения размеров файла при обрезании по квадрату (изначально делал так, потому что не хотел задавать фиксированные параметры у ширины и высоты холста, на котором картинка, чтобы универсально работало как для вертикальных, так и для горизонтальных картинок, потому что не мог получить без js размеры квадрата)

2023-01-15 21:59 UTC, Turukmokto commented
Прошу прощения, я неправильно понял условие про вписывание в квадрат и вписывал по минимальной размеренности, а не по максимальной (пофиксил)

2023-01-16 18:52 UTC, trixartem commented
Вмещаемость не работает 
![image](https://user-images.githubusercontent.com/2376007/212748429-92142d52-5cfc-46ab-95ff-622b536d9130.png)

2023-01-16 18:54 UTC, trixartem commented
> Подгружаю иконки из svg файлов в папке icons, а не из html кода

А теперь все картинки надо собрать в спрайт в один файл и позиционировать на нужной иконке(см. лекцию)

2023-01-16 19:07 UTC, trixartem commented
Не буду мучать с спрайтами, но нужно починить вмещаемость

2023-01-16 19:10 UTC, trixartem commented
✅ Принято

2023-01-16 19:10 UTC, closed without merging