Максонов Артем М3334
itmo2022-verstka/task-4 pull request #8
Opened 2023-01-03 21:44 UTC by BloodMagicLord

2023-01-23 20:57 UTC, trixartem requested changes

2023-01-23 20:57 UTC, trixartem commented on catgram/src/index.html
> +    <svg class="svg">
Картинку надо вынести в отдельный файл

2023-01-23 20:57 UTC, trixartem commented on catgram/src/index.css
> +  transform: rotateY(180deg);
Неправильно работает, если сначала повернуть картинку, а потом нажать mirror

2023-01-23 20:57 UTC, trixartem commented on catgram/src/index.css
> +.original-switcher-2:checked ~ .cat-image .image img{
Не работает, если сначала включить full-switcher

2023-01-23 20:57 UTC, trixartem commented on catgram/src/index.css
> +  height: var(--image-height);
При переключении картинка должны быть вписана в квадрат или занимать все простраство. Сейчас меняется размер квадрата

2023-01-27 21:03 UTC, BloodMagicLord commented
@trixartem Исправил 1, 2 и 3 пункты. 4-ый частично, картина немного залазит на интерфейс. Проверьте, пожалуйста; если возможно, хочу улучшить текущий балл.

2023-03-15 20:14 UTC, closed without merging