Лаврентьев Николай M3337
itmo2022-verstka/task-4 pull request #9
Opened 2023-01-07 08:01 UTC by Klanick

2023-01-23 20:59 UTC, trixartem commented
На мобилке что-то странное
![image](https://user-images.githubusercontent.com/2376007/214148746-4d3c30b3-a453-4c28-a676-e5d1cb77421a.png)

2023-01-23 21:02 UTC, trixartem requested changes

2023-01-23 21:02 UTC, trixartem commented on catgram/src/index.html
> +    <svg width="0" height="0" class="hidden">
Надо вынести в отдельный файл

2023-01-23 21:03 UTC, trixartem commented
Жду 2 фикса, остальное хорошо

2023-01-24 13:38 UTC, Klanick commented
К сожалению я не нашёл способа как сохранить градиент у лого при экспорте из sprite.svg. Поэтому всё кроме лого берётся из sprite.svg . А сам лого лежит прямо в html.

2023-01-24 20:10 UTC, trixartem commented
✅ Принято

2023-01-24 20:10 UTC, closed without merging